services:
  database:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: api
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432

  test_database:
    image: postgres:17
    environment:
      POSTGRES_DB: tests
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - 5433:5432

volumes:
  postgres_data: null